# Generated by Django 3.2.4 on 2021-08-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=20)),
                ('course', models.PositiveSmallIntegerField()),
                ('identification', models.CharField(max_length=13)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Binary', 'Binary'), ('Do not specify', 'Do not specify'), ('THey/Them', 'THey/Them')], default='Female', max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('nationality', models.CharField(choices=[('Kenyan', 'Kenyan'), ('Ugandan', 'Ugandan'), ('Rwandese', 'Rwandese'), ('South Sudanese', 'South Sudanese'), ('Tanzanian', 'Tanzanian')], default='Kenyan', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=15)),
                ('salary', models.PositiveBigIntegerField()),
                ('resume', models.FileField(upload_to='document/%Y/%m/%d')),
                ('profile_picture', models.ImageField(upload_to='images/%Y/%m/%d')),
            ],
        ),
    ]
