# Generated by Django 3.2.4 on 2021-08-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='course',
            field=models.CharField(max_length=35),
        ),
    ]
